[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/tags/v3.1.0.tar.gz"
    exact = true
    stripComponents = 1
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    executable = true
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting/themes/catppuccin"]
    type = "git-repo"
    url = "https://github.com/catppuccin/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/refs/tags/v1.20.0.tar.gz"
    exact = true
    stripComponents = 1
    executable = true
[".config/nvim/"]
    type = "git-repo"
    url = "https://github.com/rodolfolabiapari/kickstart.nvim.git"
    refreshPeriod = "168h"
[".config/bat/themes/catppuccin"]
    type = "git-repo"
    url = "https://github.com/catppuccin/bat.git"
    refreshPeriod = "168h"
[".config/sublime-text-3/Packages/Catppuccin"]
    type = "git-repo"
    url = "https://github.com/catppuccin/sublime-text.git"
    refreshPeriod = "168h"
