# Pacotes Tmux
# Installs tpm manager
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"

# Pacotes ZSH
# ZSH catppuccin Highlighting
[".local/share/zsh-syntax-highlighting-catppuccin"]
    type = "git-repo"
    url = "https://github.com/catppuccin/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"

[".local/share/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"

# Installs ohmyzsh
[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"

# Fonts for my terminals and icons
[".local/share/fonts/meslo"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Meslo.tar.xz"
    exact = true
    refreshPeriod = "168h"
    include = ["*.ttf"]

# highlight syntax
[".local/share/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"


# My neovim/nvim configuration
[".config/nvim/"]
    type = "git-repo"
    url = "https://github.com/rodolfolabiapari/kickstart.nvim.git"
    refreshPeriod = "168h"


# Pacotes Sublime
[".config/sublime-text-3/Packages/Catppuccin"]
    type = "git-repo"
    url = "https://github.com/catppuccin/sublime-text.git"
    refreshPeriod = "168h"

# bat-extras for bat command para ubuntu executar ./build --install
# no mac eh instalado via brew
[".local/share/bat-extras"]
    type = "git-repo"
    url = "https://github.com/eth-p/bat-extras.git"
    refreshPeriod = "168h"



# Binarios
# Installs bin fzf, apt has old version
# It is necessary to run ./install to install or
# upgrade fzf
[".local/share/fzf"]
    type = "git-repo"
    url = "https://github.com/junegunn/fzf.git"
    refreshPeriod = "168h"

