"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true # Recomendado para não poluir com tantas informações
command_timeout = 500 # Aumentei um pouco para chamadas de API (AWS/K8s)
palette = "tokyo-night"

format = """$directory$git_branch $git_status$git_metrics$fill $username$hostname$aws$kubernetes$terraform$gcloud$python$cmd_duration$time
$character"""

[character]
error_symbol = "[✗](bold purple)"
success_symbol = "[❯](bold green)"

# Fill character (empty space) between the left and right prompt
[fill]
symbol = "-"
style = "bold bright-black"

[directory]
truncation_symbol = "…/"
truncation_length = 8 # 0 mostra o caminho completo
fish_style_pwd_dir_length = 3
style = "bold blue"
repo_root_style = "bold cyan"
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "italic purple"

[git_status]
format = '([$ahead_behind$all_status]($style) )'
style = "bold yellow"
conflicted = '[✖ ](bold red)'
ahead = '[↑${count} ](bold green)'
behind = '[↓${count} ](bold red)'
diverged = '[↕ ](bold red)'
up_to_date = ''
untracked = '[? ](bold red)'
stashed = '[\$ ](bold purple)'
modified = '[! ](bold yellow)'
staged = '[+ ](bold green)'
renamed = '[» ](bold cyan)'
deleted = '[✘ ](bold red)'

[git_metrics]
added_style = 'bold green'
deleted_style = 'bold red'
format = 'Δ[+$added]($added_style)/[-$deleted]($deleted_style) '

[time]
disabled = false
format = "[$time]($style) "
time_format = "%T"
style = "dimmed white"

[python]
format = '[${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
show_milliseconds = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = true
show_always = true

[aws]
symbol = " "
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = "bold yellow"

[kubernetes]
symbol = "󱃾 "
#format = "at [$symbol$context]($style) "
format = '[$symbol$context( \($namespace\))]($style) in '
style = "cyan bold"
disabled = true

[terraform]
symbol = "󱁢 "
format = "[$symbol$version]($style) "
detect_extensions = ['tf', 'tfplan', 'tfstate', 'hcl', 'tfvars']

[gcloud]
symbol = " "
format = '[$symbol$account(@$domain)(\($project\))]($style) '
disabled = true



# TODO
[custom.taskwarrior]
command = "task status:pending count" # Comando que retorna o número
when = "type task" # Só executa se o taskwarrior estiver instalado
shell = ["bash", "--noprofile", "--norc"]
format = "tasks: [$output]($style) "
style = "bold purple"

[palettes.tokyo-night]
black = "#1a1b26"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
purple = "#ad8ee6"
cyan = "#449dab"
white = "#a9b1d6"
bright-black = "#414868"
bright-red = "#ff7a93"
bright-green = "#b9f27c"
bright-yellow = "#ff9e64"
bright-blue = "#7da6ff"
bright-purple = "#bb9af7"
bright-cyan = "#0db9d7"
bright-white = "#c0caf5"

