[General]
contrastOpacity=188
saveAfterCopy=true
savePath=/home/rodolfo/Pictures/flameshot
startupLaunch=true
; useGrimAdapter=true


## Sugestao do Guilherme daher
; [General]
; antialiasingPinZoom=false
; ;captureActiveMonitor=true
; contrastOpacity=76
; disabledTrayIcon=true
; filenamePattern=%F_%H-%M-%S
; savePath=/tmp/
; showAbortNotification=false
; showDesktopNotification=false
; showHelp=false
; showSelectionGeometryHideTime=3000
; showStartupLaunchMessage=false
; uiColor=#960090
; useX11LegacyScreenshot=false
;
; hl.bind("Print",function()
;     local monitor = hl.get_active_monitor()
;     hl.dispatch(hl.dsp.exec_cmd("flameshot screen -e -n " .. monitor.id))
; end)